name: Deploy .NET API to Hostinger

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Publish .NET Application
        run: dotnet publish -c Release -o ./publish

      - name: Deploy to Hostinger via SSH
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.160.238.36.109 }}
          username: ${{ secrets.root }}
          key: ${{ secrets.ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCiTYpwCNRZxIq/5oU0PolCBNx/mnFjPUf2vDCXGGZpp5ud845M8LPbnF0lNZd2CCfKx4YHyrT39a6V+BpnUq/jCIUvXSMifFgQDFiwfcPrT4lN5GdEKrbPMhw0Q/GkqIO+W62F2BxxgvHO4v4JsRY5dS8QprmiaZ8Yem/NQJ388kK260hAjUyUIdRNw/6iOMTLFvTTDAQ+BEuWL0dy64cSzfbGbgUk2Ouxbp8fjRsRRhiyPw29X3U/A9YUGq05fIYKR3I4SSkLZ8uqPJkSyjfBZqwh1CegOhb+0qwnotYaUmyNDfxtFCl1lEwZZh/6KVrSNDAlSks5EVByi5bsSW6T rsa-key-20241217 }}
          source: "./publish/*"
          target: "/var/www/jssports"

      - name: Restart .NET Service
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.160.238.36.109 }}
          username: ${{ secrets.root }}
          key: ${{ secrets.ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCiTYpwCNRZxIq/5oU0PolCBNx/mnFjPUf2vDCXGGZpp5ud845M8LPbnF0lNZd2CCfKx4YHyrT39a6V+BpnUq/jCIUvXSMifFgQDFiwfcPrT4lN5GdEKrbPMhw0Q/GkqIO+W62F2BxxgvHO4v4JsRY5dS8QprmiaZ8Yem/NQJ388kK260hAjUyUIdRNw/6iOMTLFvTTDAQ+BEuWL0dy64cSzfbGbgUk2Ouxbp8fjRsRRhiyPw29X3U/A9YUGq05fIYKR3I4SSkLZ8uqPJkSyjfBZqwh1CegOhb+0qwnotYaUmyNDfxtFCl1lEwZZh/6KVrSNDAlSks5EVByi5bsSW6T rsa-key-20241217 }}
          script: |
            sudo systemctl restart myapp.service
            sudo systemctl status myapp.service
